# Pull base image
FROM python:latest

# Set working directory
WORKDIR /app

# Copy the source code to the container
COPY . /app/

# Install the dependencies
RUN pip install -r requirements.txt

# Expose the port the app runs on
EXPOSE 8000

# Command to run the project
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
