version: "3.8"

services:
  intranet:
    build:
      context: .
    container_name: my_project
    command: sh -c "echo hello"
    env_file:
      - ".env"
    ports:
      -"8000":"8000"
    networks:
      - my_test_net
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MY_SQL_DATABASE="testdb"
      - MY_SQL_PASS="root"
    ports:
      -"3306":"3306"
    volumes:
      -./mysql-data:/var/lib/mysql
    networks:
      - my_test_net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  mysql-data:

networks:
  my_test_net:


