# stage 1 base image size is 994mb
FROM python:3.7 AS builder

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt into the container at /app
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# stage 2 base image size is 125mb

FROM python:3.7-slim

WORKDIR /app

# Copy the built dependencies from the backend stage
COPY --from=builder /usr/local/lib/python3.7/site-packages  /usr/local/lib/python3.7/site-packages

# Copy the application code from the backend stage
COPY --from=backend /app /app

# Expose port 5000 for the Flask application
EXPOSE 8000

# Define the default command to run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
